name: Pull Request

on: 
  pull_request:
    branches:
      - main

jobs:
  coding-standards:
    name: Coding Standards
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          coverage: pcov
          tools: composer

      - name: Install dependencies
        run: |
          npm install --no-audit --no-fund --prefer-offline --progress=false
          composer install --no-interaction --no-progress --no-suggest --optimize-autoloader
      
      - name: Run Build
        run: npm run build
      
      - name: Lint JS
        run: npm run lint:js
      - name: Lint CSS
        run: npm run lint:css
      - name: Lint PHP
        run: composer run phpcs
